/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Footer: typeof import('./src/components/Layout/Footer.vue')['default']
    MainNav: typeof import('./src/components/Layout/MainNav.vue')['default']
    Model: typeof import('./src/components/Model.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SideBar: typeof import('./src/components/Layout/SideBar.vue')['default']
    SidebarItem: typeof import('./src/components/Layout/SidebarItem.vue')['default']
    VanCollapse: typeof import('vant/es')['Collapse']
    VanCollapseItem: typeof import('vant/es')['CollapseItem']
    VanPopup: typeof import('vant/es')['Popup']
  }
}
